Bug 1880603: controller/helpers.go: de-duplicate ign spec 2 passwdUsers
openshift/machine-config-operator pull request #2103
Opened 2020-09-18 21:43 UTC by yuqi-zhang

In spec 2 MC merging, the passwd user sections are merged into each
other. This means in practice that there will be multiple entries
for a "core" user if you define multiple ssh keys via multiple MCs.
This will fail the translation to spec 3 upon upgrading, so we need
to also de-duplicate this section by merging sshkeys into one "core"
user. Also add explicit check for other users here (since we don't
support them).

2020-09-18 21:44 UTC, yuqi-zhang commented
/hold
pending manual tests

2020-09-18 22:19 UTC, cgwalters requested changes
Looks reasonable to me, one requested change.

Do we have a sense of how common this is or more precisely what the reproducer scenario is?  Is this something like a cluster where the admin created *two* ssh key MachineConfig fragments?

2020-09-18 22:24 UTC, yuqi-zhang commented
> Do we have a sense of how common this is or more precisely what the reproducer scenario is? Is this something like a cluster where the admin created two ssh key MachineConfig fragments?

Yes. Reproducer is on any cluster on version 4.5 or before, create another machineconfig that has a passwd -> sshauthorizedkeys section. Basically add a key to the cluster.

2020-09-18 22:25 UTC, yuqi-zhang commented on pkg/controller/common/helpers.go
> +	outUser := users[len(users)-1]
Right, I think in that case the MCO always creates a dummy core user (if I recall correctly). But to be safe I will check for empty user section here. Thanks!

2020-09-21 13:16 UTC, ashcrow commented
Unit failure:
```
FAIL	github.com/openshift/machine-config-operator/pkg/controller/common [build failed]
<snip/>
--- FAIL: TestEncapsulated (0.02s)
panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]
```

2020-09-21 15:38 UTC, yuqi-zhang commented
/test unit

2020-09-21 17:13 UTC, yuqi-zhang commented
/hold cancel

Fixed tests, added check for empty user, tested to work on a manual upgrade

2020-09-21 18:40 UTC, cgwalters approved these changes
/lgtm

2020-09-22 00:45 UTC, merged