Bug 1873556: export proxy variables to be taken in account
openshift/machine-config-operator pull request #2279
Opened 2020-12-02 21:51 UTC by EmilienM

In order to have the proxy variables (HTTP_PROXY, HTTPS_PROXY and
NO_PROXY), we need to `export` them otherwise then don't end up being
loaded in the environment and it causes issues if a proxy is used,
when pulling an image from a registry for example.

Signed-off-by: Emilien Macchi <emilien@redhat.com>
(cherry picked from commit f41b1d2ae7feea9aedfbd62143baefdf950c8569)

2020-12-02 21:52 UTC, EmilienM commented
/assign cgwalters

2020-12-02 21:53 UTC, EmilienM commented
I'll refresh BZ bot once it pass QA

2020-12-03 13:09 UTC, EmilienM commented
/bugzilla refresh

2020-12-09 14:09 UTC, mandre commented
/bugzilla refresh
/retest

2020-12-09 14:13 UTC, mandre requested changes
We'll need to fix all on-prem platforms, not just baremetal.
- https://github.com/openshift/machine-config-operator/blob/release-4.6/templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
- https://github.com/openshift/machine-config-operator/blob/release-4.6/templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- https://github.com/openshift/machine-config-operator/blob/release-4.6/templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml

2020-12-09 19:20 UTC, kikisdeliveryservice commented
/retest

2020-12-09 19:23 UTC, kikisdeliveryservice commented
/bugzilla refresh

2020-12-09 20:40 UTC, kikisdeliveryservice commented
/retest

2020-12-09 20:50 UTC, kikisdeliveryservice commented
Underlying BZ is for Openstack, so @EmilienM will need to update templates and double check it fixes in 4.6 then we can merge :+1:

2020-12-09 20:52 UTC, kikisdeliveryservice commented
/assign @celebdor

2020-12-10 13:19 UTC, mandre reviewed
/lgtm

2020-12-10 13:19 UTC, EmilienM commented
@kikisdeliveryservice hi, the PR is now updated, and IMO ready to merge. Thanks

2020-12-10 13:20 UTC, pierreprinetti commented
/lgtm

2020-12-10 18:04 UTC, bcrochet commented
/lgtm

2020-12-10 18:05 UTC, kikisdeliveryservice approved these changes

2020-12-10 19:59 UTC, eparis commented
/bugzilla refresh

2020-12-10 22:40 UTC, kikisdeliveryservice commented
/skip

2020-12-11 00:39 UTC, kikisdeliveryservice commented
this okd test is completely red but the bot doesn't listen to me..

/skip

2020-12-11 00:39 UTC, eparis commented
Hey, the bot listened that time!

2020-12-11 00:43 UTC, merged

2020-12-14 22:05 UTC, cybertron commented
/cherry-pick release-4.5