[On-prem] - fix grep syntax for Keepalived remove-vips
openshift/machine-config-operator pull request #2548
Opened 2021-04-27 09:18 UTC by yboaron

https://bugzilla.redhat.com/show_bug.cgi?id=1931505  reproduced in QE folks environments even with the latest version,
seems that changing grep syntax from ' to " solved the problem locally.

2021-04-27 09:20 UTC, yboaron commented
/retitle Bug 1931505: [On-prem] - fix grep syntax for Keepalived remove-vips

2021-04-27 11:14 UTC, stbenjam commented
/bugzilla refresh

2021-04-27 11:36 UTC, mandre commented on templates/common/on-prem/files/keepalived.yaml
> +            cidr=$(ip -o a | grep "\s${address}/" | awk '{print $4}')
Nit: I'd personally remove the grep in the middle and rely on awk for filtering:
```suggestion
            interface=$(ip -o a | awk "/\s${address}/ {print \$2}")
            cidr=$(ip -o a | awk "/\s${address}/ {print \$4}")
```

2021-04-27 14:27 UTC, cybertron requested changes
Argh, I must have added the wrong quotes when I was fixing the vsphere job. :-(

One thing that needs to be fixed inline, but otherwise lgtm.

2021-04-27 14:27 UTC, cybertron commented on templates/common/on-prem/files/keepalived.yaml
> +            interface=$(ip -o a | awk "/\s${address}/ {print \$2}")
This doesn't do quite the same thing. The awk needs to be:

awk "/\s${address}\// {print \$2}"

We need to make sure we match exactly the VIP and not a substring.

2021-04-27 16:00 UTC, cybertron commented
/lgtm
/test e2e-openstack
/test e2e-ovirt
/test e2e-vsphere
/cc @Gal-Zaidman @jcpowermac @patrickdillon

2021-04-27 17:27 UTC, cybertron approved these changes
/lgtm

Let's see if the bot likes me better now...

2021-04-27 17:28 UTC, cybertron commented
Progress! Let's see if it will run the jobs too. :-)

/test e2e-openstack
/test e2e-ovirt
/test e2e-vsphere
/cc @Gal-Zaidman @jcpowermac @patrickdillon

2021-04-27 19:42 UTC, cybertron commented
/retest

That's...a lotta red. Two of the on-prem platforms passed though so this is likely fine. I see in the metal-ipi job that it did the right thing as well:
```
2021-04-27T16:27:07.587096146Z + remove_vip fd2e:6f44:5dd8:c956::4
2021-04-27T16:27:07.587125393Z + address=fd2e:6f44:5dd8:c956::4
2021-04-27T16:27:07.588005687Z ++ ip -o a
2021-04-27T16:27:07.588067999Z ++ awk '/\sfd2e:6f44:5dd8:c956::4\// {print $2}'
2021-04-27T16:27:07.590997589Z + interface=br-ex
2021-04-27T16:27:07.591792615Z ++ ip -o a
2021-04-27T16:27:07.592046919Z ++ awk '/\sfd2e:6f44:5dd8:c956::4\// {print $4}'
2021-04-27T16:27:07.595184196Z + cidr=fd2e:6f44:5dd8:c956::4/128
2021-04-27T16:27:07.595184196Z + '[' -n br-ex ']'
2021-04-27T16:27:07.595212406Z + ip a del fd2e:6f44:5dd8:c956::4/128 dev br-ex
```

2021-04-28 06:48 UTC, Gal-Zaidman commented
/lgtm

2021-04-28 07:56 UTC, yboaron commented
I sent a test PR (use grep with " for VIP filtering) to check CI gates with grep instead of awk .. 


[1] https://github.com/openshift/machine-config-operator/pull/2550

2021-04-28 07:58 UTC, yboaron commented
/retest

2021-04-28 12:12 UTC, mandre commented
Seems to be working for ovirt and openstack at least.
/retest
/lgtm

2021-04-29 06:14 UTC, yboaron commented
/retest

2021-04-29 16:43 UTC, yboaron commented
/retest

2021-04-30 11:29 UTC, stbenjam commented
/test e2e-metal-ipi

2021-04-30 14:49 UTC, cybertron commented
/test e2e-vsphere

2021-05-01 13:17 UTC, merged