[ON-PREM] HAProxy - Verify that the NM prepender applied using initcontainer
openshift/machine-config-operator pull request #2650
Opened 2021-06-30 14:23 UTC by yboaron

The HAProxy-monitor container should start running only after applying the NM prepender script
(to be able to communicate with api-int: kube-api).

We noticed that in the current implementation (Liveness probe) we may break the API traffic for a
few seconds even because of changes in host's resolv.conf that aren't relevant to the HAProxy monitor.

This PR replaces the Liveness probe that compares resolv.conf and host's resolv.conf
with an init container.

2021-06-30 16:39 UTC, cybertron requested changes
This doesn't solve the same problem as the liveness probe. We need to be able to react to resolv.conf changes after the pod is running. If we only use an init container then any DNS changes will require a manual restart of the haproxy-monitor.

We should probably find some way to make the restart more graceful. When the liveness probe fails, does the monitor remove the iptables rules then or does it happen after it restarts? As I recall, liveness probe failures trigger hard restarts of the container that don't allow for cleanup, so I'm guessing the latter.

2021-07-05 11:28 UTC, yboaron commented
> This doesn't solve the same problem as the liveness probe. We need to be able to react to resolv.conf changes after the pod is running. If we only use an init container then any DNS changes will require a manual restart of the haproxy-monitor.

Well, I'm not sure that we need to react to changes in resolv.conf; 

IIRC, the reason that the liveness probe was added is the following race condition:
1. HAProxy-monitor start running 
2. NM resolve.conf  prepender script applied  

In this case, the resolv.conf  in monitor container doesn't point to local CoreDNS --> monitor container can't resolve api-int .

Don't you think that an init container verifying api-int is resolvable is sufficient for such cases? 

BTW, for keepalived, we have an init container [1] that renders keepalived.conf and also addresses the race described above (monitor container reads nodes details from kube-api).


[1] https://github.com/openshift/machine-config-operator/blob/master/templates/common/on-prem/files/keepalived.yaml#L37

> We should probably find some way to make the restart more graceful. When the liveness probe fails, does the monitor remove the iptables rules then or does it happen after it restarts? As I recall, liveness probe failures trigger hard restarts of the container that don't allow for cleanup, so I'm guessing the latter.

2021-07-07 20:59 UTC, cybertron approved these changes
Okay, yeah. If there are DNS changes after the initial startup the coredns-monitor will handle them, and since we're using that as our primary DNS server it won't matter if the haproxy container gets out of date.

/lgtm

2021-07-07 21:00 UTC, cybertron commented
/test e2e-openstack
/test e2e-ovirt
/test e2e-vsphere
/cc @mandre @Gal-Zaidman @jcpowermac @patrickdillon

2021-07-08 07:01 UTC, Gal-Zaidman commented
/lgtm

2021-07-08 07:09 UTC, eslutsky commented
/lgtm

2021-07-08 11:15 UTC, yboaron commented
/test e2e-metal-ipi

2021-07-08 13:54 UTC, ardaguclu commented
/test e2e-metal-ipi

2021-07-08 15:42 UTC, cybertron commented
/test e2e-openstack
/test e2e-vsphere

2021-07-08 18:58 UTC, sadasu commented
/retest

2021-07-09 06:54 UTC, mandre reviewed
Shouldn't this reference a bz to give us the opportunity to more easily backport?
LGTM otherwise.

2021-07-09 07:56 UTC, hardys commented
> Shouldn't this reference a bz to give us the opportunity to more easily backport?
> LGTM otherwise.

@ardaguclu raised https://bugzilla.redhat.com/show_bug.cgi?id=1980658 which relates to this issue so we can use that I think

2021-07-09 07:58 UTC, hardys commented
/retitle Bug 1980658: ON-PREM] HAProxy - Verify that NM prepender script was applied using initcontainer

2021-07-09 08:00 UTC, hardys commented
/bugzilla refresh

2021-07-09 08:13 UTC, mandre commented
/lgtm

2021-07-09 13:41 UTC, jcpowermac commented
/test e2e-vsphere

2021-07-09 14:32 UTC, stbenjam commented
/assign @kikisdeliveryservice @sinnykumari @yuqi-zhang

PTAL :pray:

2021-07-09 15:06 UTC, jcpowermac commented
single test failure that was also in the nightly
/lgtm

2021-07-12 08:47 UTC, sinnykumari approved these changes
LGTM. PR has been reviewed and approved by on-perm teams.

2021-07-12 15:48 UTC, stbenjam commented
/test e2e-agnostic-upgrade

2021-07-12 17:54 UTC, merged

2021-07-25 10:44 UTC, yboaron commented
/cherry-pick release-4.8