Updating openshift libraries
openshift/machine-config-operator pull request #2772
Opened 2021-09-22 15:27 UTC by kwoodson

2021-09-22 16:36 UTC, kwoodson commented
Fixed the feature gate tests. unit tests now pass.

2021-09-22 17:04 UTC, kwoodson commented
Looks like the e2e-agnostic-upgrade is failing because of quota.
```
The directory object quota limit for the Tenant has been exceeded. Please ask your administrator to increase the quota limit or delete objects to reduce the used quota."
```

2021-09-22 17:41 UTC, kwoodson commented
/test e2e-agnostic-upgrade

2021-09-23 17:27 UTC, kikisdeliveryservice requested changes
Can you explicitly say in the commit what libraries you are updating? ie openshift/api client-go library-go??

2021-09-23 17:27 UTC, kikisdeliveryservice commented on templates/master/01-master-kubelet/_base/files/kubelet.yaml
> +      PodSecurity: true
@rphillips FYI

2021-09-23 23:57 UTC, kwoodson commented
@kikisdeliveryservice I've updated the commit message to include the library names.

2021-09-27 15:09 UTC, sinnykumari commented
PTAL since this PR adds explicitly  `PodSecurity: true` into kubelet cofnig.
/assign @rphillips

2021-09-27 16:47 UTC, rphillips commented
/hold for discussion around PodSecurity on by default in openshift/api (alpha level feature)

2021-09-27 17:28 UTC, rphillips commented
/hold cancel
/lgtm

this feature flag only changes the API server.

2021-09-28 08:47 UTC, sinnykumari approved these changes

2021-09-29 00:57 UTC, merged