Add PowerVS platform
openshift/machine-config-operator pull request #2801
Opened 2021-10-15 15:00 UTC by Prashanth684

Enable Power VS(Virtual Servers) as a platform. PowerVS is an extension of IBMCloud which supports deploying ppc64le VMs.
Details here: https://github.com/openshift/enhancements/pull/736

The hostname for the VMs are set through afterburn which reads the metadata provided through the config drive which is the primary mechanism through which ignition and hostname are provided.
(https://github.com/coreos/afterburn/pull/592)

Cross referencing some other PRs for completeness:
https://github.com/openshift/installer/pull/5270
https://github.com/openshift/installer/pull/5224 (closed, WIP to split into multiple PRs)

ova images for PowerVS are already generated today:
https://github.com/coreos/coreos-assembler/pull/2200
https://github.com/coreos/coreos-assembler/pull/2361

2021-10-15 15:18 UTC, Prashanth684 commented
/cc @clnperez @mkumatag

2021-10-19 19:32 UTC, clnperez commented
I'll also add that we tested with these changes and were able to stand up a cluster in Power VS.

2021-10-19 19:47 UTC, cgwalters reviewed
Looks sane to me!

2021-10-20 03:27 UTC, mkumatag requested changes

2021-10-20 03:27 UTC, mkumatag commented on pkg/controller/template/render.go
> +	case configv1.AWSPlatformType, configv1.AzurePlatformType, configv1.GCPPlatformType, configv1.OpenStackPlatformType, configv1.PowerVSPlatformType, configv1.VSpherePlatformType:
@Prashanth684 this is not required for powervs platform, this applies only for the in-tree cloud-providers

2021-10-29 03:54 UTC, merged