Bug 2034364: Set proper InvolvedObject when using library-go EventRecorder
openshift/machine-config-operator pull request #2893
Opened 2021-12-23 16:24 UTC by mkenigs

Otherwise this will cause "Error creating event &Event" errors
Related to Bug 2034364, overlooked in
https://github.com/openshift/machine-config-operator/pull/2833

Replaces https://github.com/openshift/machine-config-operator/pull/2891

2021-12-23 16:26 UTC, mkenigs commented
/cc @soltysh do I have to have a different recorder for every kind like this?

2022-01-05 09:54 UTC, soltysh commented
> @soltysh do I have to have a different recorder for every kind like this?

theoretically - yes, but I'd suggest creating a single recorder and link that only with deployment and not with every possible resource.

2022-01-05 09:56 UTC, soltysh requested changes

2022-01-05 09:56 UTC, soltysh commented on pkg/operator/operator.go
> +			APIVersion: "apps/v1",
This is wrong, you're hardcoding `APIVersion` and you're using `newRecorder` for kinds outside `apps/v1` group. As mentioned elsewhere, I'd suggest creating a single recorder tied with just the MCO deployment, which should be sufficient.

2022-01-06 15:20 UTC, mkenigs commented
> > @soltysh do I have to have a different recorder for every kind like this?
> 
> theoretically - yes, but I'd suggest creating a single recorder and link that only with deployment and not with every possible resource.

So would you suggest passing an empty recorder in instances like this (need a recorder for a `CustomResourceDefinition`)? https://github.com/openshift/machine-config-operator/pull/2893/files#diff-3e205577bec1a1d1711df8bfeff30e63f044b24cfbdc69bbd7d0052fdc881891L382

Or am I misunderstanding and I can set the recorder's kind to `Deployment` and still use it for the CRD?

2022-01-11 11:43 UTC, soltysh commented
@mkenigs I was suggesting one recorder pointing to MCO deployment and use that in most places, if not all.

2022-01-11 16:54 UTC, mkenigs commented
Oh okay then I guess maybe we should just reopen and merge your original PR? Sorry I misunderstood how this is supposed to work

2022-01-25 22:24 UTC, mkenigs commented
/bugzilla refresh

2022-01-25 23:12 UTC, kikisdeliveryservice commented
/retest-required

2022-01-26 00:12 UTC, yuqi-zhang commented
/test e2e-aws

2022-01-26 00:49 UTC, yuqi-zhang approved these changes
Tentatively approving the general code, some questions/concerns:

So looking at gcp-op (install cluster, run MCO e2e) it looks like we do have some additional event logging at the beginning that fail due to waiting for apiserver https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2893/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1486006930555015168/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-operator-69c597d945-66st6_machine-config-operator.log

Which seems fine since it does eventually resolve (and just log the pool syncs later). It is still a bit noisy but better than before. I assume those events are normal?

> theoretically - yes, but I'd suggest creating a single recorder and link that only with deployment and not with every possible resource.

I'm not the most familiar with how this works out. In the MCO we currently use the recorder when applying:
 - secrets
 - clusterrole
 - rolebinding
 - clusterrolebinding

And interestingly not the daemonset/deployment since we still use MCO code which do not invoke the recorder yet. @soltysh are you saying that with the singular hardcoded `Deployment` recorder we can cover all of the above cases?

2022-01-27 00:07 UTC, yuqi-zhang commented
Given that:
1. This PR fixes the log spam
2. The PR does not as far as I can tell cause any other eventing issues
3. This PR passed all the required tests at least once

Going to go ahead and lgtm so we can try to herd this past CI before code freeze. We can follow up on whether we should be creating different recorders per-object type as a follow up.

/lgtm

2022-01-27 08:39 UTC, kikisdeliveryservice commented
/retest-required

2022-01-27 19:28 UTC, kikisdeliveryservice commented
/test e2e-agnostic-upgrade

2022-01-28 04:54 UTC, merged