WIP: [release-4.11] OCPBUGS-3507: On-prem: Ensure resolv-prepender respects NM dispatcher timeout
openshift/machine-config-operator pull request #3422
Opened 2022-11-18 18:59 UTC by martinkennelly

Not a clean cherry-pick of 1b97dcc2390e3f76f39dfc732c9124030c5f7c5e from 4.12

Needed to replace 2 lines with:
```
                "{{ onPremPlatformAPIServerInternalIP . }}" \
                "{{ onPremPlatformIngressIP . }}")
```

2022-11-18 19:01 UTC, martinkennelly commented
/jira refresh

2022-11-18 22:26 UTC, martinkennelly commented
/retest
/test e2e-metal-ipi
/test e2e-metal-ipi-ovn-dualstack
/test e2e-metal-ipi-ovn-ipv6
/test e2e-ovirt
/test e2e-vsphere
/test e2e-vsphere-upgrade
/test e2e-ovirt-upgrade
/test e2e-metal-assisted

2022-11-21 12:05 UTC, martinkennelly commented
/retest

# CI Failures
## e2e-metal-ipi
Infra setup failure unrelated to this PR

## e2e-metal-ipi-ovn-dualstack
Opened an issue in CMO to tackle this: https://issues.redhat.com/browse/OCPBUGS-3923
Unrelated to this PR.

2022-11-21 15:30 UTC, martinkennelly commented
/test e2e-metal-ipi

2022-11-22 13:06 UTC, vrutkovs commented
/test okd-e2e-vsphere

2022-11-23 10:19 UTC, martinkennelly commented
@vrutkovs your command failed. How can we test this against okd?

2022-11-23 10:20 UTC, martinkennelly commented
/jira refresh

2022-11-23 19:03 UTC, vrutkovs requested changes
/hold

This will break OKD

2022-11-23 19:03 UTC, vrutkovs commented on templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
> +                    if [[ ! -f "${"KNICONFPATH"} ]] || [[ ! -f "${"KNICONFDONEPATH"} ]] || ! cmp --silent "${KNICONFPATH}" "${KNICONFTMPPATH}"; then
```suggestion
                    if [[ ! -f "${KNICONFPATH} ]] || [[ ! -f "${KNICONFDONEPATH} ]] || ! cmp --silent "${KNICONFPATH}" "${KNICONFTMPPATH}"; then
```

2022-11-23 19:12 UTC, vrutkovs commented
>How can we test this against okd?

Weird, release-4.11 is the only branch which is not covered. Adding OKD tests in https://github.com/openshift/release/pull/34283

2022-11-26 11:38 UTC, vrutkovs commented on templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
> +                        mv -f "${KNICONFTMPPATH}" "${KNICONFPATH}"
```suggestion
                        mv -f "${KNICONFTMPPATH}" "${KNICONFPATH}"
                        chown systemd-resolve:systemd-resolve "${KNICONFPATH}"
                        chcon system_u:object_r:etc_t:s0 "${KNICONFPATH}"
```
tmp file has invalid permissions and SELinux label

2022-11-28 20:36 UTC, yuqi-zhang commented
The 4.12 branch commit referenced (https://github.com/openshift/machine-config-operator/commit/1b97dcc2390e3f76f39dfc732c9124030c5f7c5e) doesn't seem to have some of the fixes above (e.g. selinux). Should we fix that in 4.12 first before continuing with this backport?

2022-11-29 06:52 UTC, vrutkovs commented
Yeah, still fixing master/release-4.12

2022-11-29 21:32 UTC, vrutkovs commented
/test okd-e2e-vsphere

2022-11-30 07:48 UTC, vrutkovs commented on templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
> +                        mv -f "${KNICONFTMPPATH}" "${KNICONFPATH}"
Or simply `cat "${KNICONFTMPPATH}" > "${KNICONFPATH}"`

2022-11-30 07:49 UTC, vrutkovs commented
/hold cancel

OKD vsphere install passes (fails on imagestream import which is a known issue)

2022-12-07 16:50 UTC, martinkennelly commented
/retest

2022-12-09 10:46 UTC, martinkennelly commented
/test e2e-metal-ipi
/test e2e-metal-ipi-ovn-dualstack
/test e2e-metal-ipi-ovn-ipv6
/test e2e-ovirt
/test e2e-vsphere
/test e2e-vsphere-upgrade
/test e2e-ovirt-upgrade
/test e2e-metal-assisted
/test okd-e2e-vsphere

2022-12-09 10:52 UTC, martinkennelly commented
@vrutkovs I cherry-picked your commits from 4.12. Conflict observed for commit 0e80c65d7c8bac64e5214af4ba4aae67043c857f was for these two lines:
```
      "{{ onPremPlatformAPIServerInternalIP . }}" \
      "{{ onPremPlatformIngressIP . }}")
```

No conflict for c5a078fbb36c753efdd01b3f20b67a226d52cd88

2022-12-09 14:49 UTC, martinkennelly commented
/retest

2022-12-12 09:57 UTC, martinkennelly commented
/retest
Unrelated test failures.

2022-12-13 13:58 UTC, martinkennelly commented
/test e2e-metal-ipi-ovn-dualstack 
/test okd-e2e-vsphere

2022-12-13 14:00 UTC, martinkennelly commented
@vrutkovs can i get your review (and hopeful blessing) for this?

2022-12-13 22:50 UTC, yuqi-zhang approved these changes
/label backport-risk-assessed

/hold for QE approval

Would this be verifiable by someone (Itay maybe?) pre-merge?

2022-12-14 10:37 UTC, martinkennelly commented
> /label backport-risk-assessed
> 
> /hold for QE approval
> 
> Would this be verifiable by someone (Itay maybe?) pre-merge?

Ill ask him can he do it on the jira issue. Thank you.

2022-12-15 11:19 UTC, martinkennelly commented
@anuragthehatter PTAL
Testing will be done post merge using a nightly after consulting with QE due to the complex setup required to validate this fix. See the associated issue comments for more details.

2023-01-26 12:35 UTC, martinkennelly commented
@anuragthehatter PTAL. Thank you.

2023-01-31 16:08 UTC, anuragthehatter commented
/assign @rbbratta  PTAL

2023-02-02 16:23 UTC, rbbratta commented
/label cherry-pick-approved

2023-02-03 12:01 UTC, martinkennelly commented
/unhold

2023-02-03 12:26 UTC, martinkennelly commented
/test e2e-agnostic-upgrade

2023-02-03 12:27 UTC, martinkennelly commented
/test e2e-metal-ipi-ovn-dualstack

2023-02-03 18:28 UTC, merged