MCO-1152: Add e2e tests for NodeDisruptionPolicy
openshift/machine-config-operator pull request #4365
Opened 2024-05-14 19:58 UTC by djoshy

**- What I did**

**- How to verify it**

**- Description for the changelog**

2024-05-14 20:00 UTC, djoshy commented
/test e2e-gcp-op-techpreview

2024-05-15 15:02 UTC, djoshy commented
/test e2e-gcp-op-techpreview

2024-05-15 15:18 UTC, djoshy commented
/test e2e-gcp-op-techpreview

2024-05-21 18:30 UTC, djoshy commented
/test unit

2024-05-23 12:55 UTC, djoshy commented
/retest-required

2024-05-23 15:16 UTC, djoshy commented
/test e2e-gcp-op-techpreview

2024-05-30 13:30 UTC, djoshy commented
/test all

2024-05-30 15:30 UTC, cheesesashimi requested changes
Overall this looks great! I just have a few small suggestions.

2024-05-30 15:30 UTC, cheesesashimi commented on test/e2e-techpreview/nodedisrupt_test.go
> +				t.Parallel()
praise: Nice! I want to be able to parallelize more in our e2e suite.

2024-05-30 15:30 UTC, cheesesashimi commented on pkg/daemon/update.go
> +			err = fmt.Errorf("NodeDisruptionPolicyStatus is not up to date")
thought: I just took a look at why this was written like this. Basically, we use the variable `err` for _both_ the value returned by `wait.PollUntilContextTimeout()` in addition to what is inside the closure that `wait.PollUntilContextTimeout()` executes. Its a bit confusing as to whether we should stop polling in that case or keep going and deal with the error later. If we want to keep going and deal with the error later, using the [Aggregate](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/errors/errors.go#L46) coupled with an appropriate deduplication function could help readability.

(To be clear: I am not asking you to change this as part of this PR. It's just a thought I'm putting here for posterity.)

2024-05-30 15:56 UTC, djoshy commented on test/e2e-techpreview/nodedisrupt_test.go
> +			ac = mcoac.NodeDisruptionPolicySpecFile().WithPath(fileName).WithActions(mcoac.NodeDisruptionPolicySpecAction().WithType(action.Type).WithReload(mcoac.ReloadService().WithServiceName(action.Reload
Will attempt to clean this up, thanks (:

2024-05-30 15:58 UTC, djoshy commented on test/helpers/utils.go
> +// Asserts that a given file exists on the underlying node and returns the content of the file.
I believe we have helpers that checks if a file exists/does not exist, but not one that grabs the content in the file :)

2024-05-30 16:06 UTC, djoshy commented on test/e2e-techpreview/nodedisrupt_test.go
> +	machineConfigClient := machineconfigclientset.NewForConfigOrDie(cs.GetRestConfig())
Oh was not aware of that - I'll try to use this instead! Thanks!

2024-05-30 16:13 UTC, djoshy commented on pkg/daemon/update.go
> +			err = fmt.Errorf("NodeDisruptionPolicyStatus is not up to date")
Sorry about the structure being confusing! My thought process to use it was the following:
- If we encounter an error, we don't want to keep going in the polling function. We want to try again after an interval of time.
- If we timeout on the polling function, we want the last error we encountered to be reported. Hence the use of the same variable inside and outside of the function.

I hope that clears up why I went with the last error vs aggregation. Any of the errors within the polling loop are fatal, with the earlier ones being slightly more fatal than the ones following.

2024-05-31 16:11 UTC, djoshy commented on test/e2e-techpreview/nodedisrupt_test.go
> +			ac = mcoac.NodeDisruptionPolicySpecFile().WithPath(fileName).WithActions(mcoac.NodeDisruptionPolicySpecAction().WithType(action.Type).WithReload(mcoac.ReloadService().WithServiceName(action.Reload
I was able to break this down as suggestion, and create a new helper - making it overall a lot cleaner and re-usable. Thanks so much for this suggestion!

2024-06-03 13:51 UTC, djoshy commented
/retest-required

2024-06-03 13:55 UTC, cheesesashimi commented on pkg/daemon/update.go
> +			err = fmt.Errorf("NodeDisruptionPolicyStatus is not up to date")
Ahhh that makes sense, thanks for the clarification!

2024-06-03 14:18 UTC, djoshy commented
/retest-required

2024-06-03 17:51 UTC, djoshy commented
/retest-required

2024-06-04 13:04 UTC, djoshy commented
/retest-required

2024-06-04 20:42 UTC, djoshy commented on pkg/daemon/update.go
> +			err = fmt.Errorf("NodeDisruptionPolicyStatus is not up to date")
I assigned a new variable so it is easier to read what I'm trying to do (:

2024-06-06 10:25 UTC, sinnykumari reviewed
changes looks good.
/approve
Will see if Zack have any final thoughts and would like to tag lgtm.

2024-06-06 13:14 UTC, djoshy commented
/test all

2024-06-07 18:34 UTC, cheesesashimi commented
/lgtm
/approve

2024-06-07 18:45 UTC, djoshy commented
/hold

just in case QE wants to take a look

2024-06-07 18:45 UTC, djoshy commented
/test all

2024-06-10 17:40 UTC, djoshy commented
Discussed with @sergiordlr , as this is mainly e2es, pre merge QE is not required. Unholding.

/unhold
/retest-required

2024-06-10 20:15 UTC, merged